openapi: 3.0.0
info:
  title: Microsoft Graph API
  version: 1.0
servers:
  - url: https://graph.microsoft.com/v1.0/
paths:
  /users/{user_id}:
    get:
      summary: Get user profile
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: User profile data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfile'
components:
  schemas:
    UserProfile:
      type: object
      properties:
        displayName:
          type: string
        mail:
          type: string
